# Cambia estos valores por los tuyos
spring.datasource.url=jdbc:postgresql://localhost:5432/literalura
spring.datasource.username=Developer
spring.datasource.password=@Jlien-0814@

# Spring crea las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
